// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	coupons "TugasDay23/features/coupons"

	jwt "github.com/golang-jwt/jwt/v5"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetKupon provides a mock function with given fields: page, pageSize
func (_m *Service) GetKupon(page int64, pageSize int64) ([]coupons.Coupon, coupons.Pagination, error) {
	ret := _m.Called(page, pageSize)

	var r0 []coupons.Coupon
	var r1 coupons.Pagination
	var r2 error
	if rf, ok := ret.Get(0).(func(int64, int64) ([]coupons.Coupon, coupons.Pagination, error)); ok {
		return rf(page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(int64, int64) []coupons.Coupon); ok {
		r0 = rf(page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coupons.Coupon)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64) coupons.Pagination); ok {
		r1 = rf(page, pageSize)
	} else {
		r1 = ret.Get(1).(coupons.Pagination)
	}

	if rf, ok := ret.Get(2).(func(int64, int64) error); ok {
		r2 = rf(page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetKuponByUser provides a mock function with given fields: token
func (_m *Service) GetKuponByUser(token *jwt.Token) ([]coupons.Coupon, error) {
	ret := _m.Called(token)

	var r0 []coupons.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token) ([]coupons.Coupon, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token) []coupons.Coupon); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coupons.Coupon)
		}
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TambahKupon provides a mock function with given fields: token, newCoupon
func (_m *Service) TambahKupon(token *jwt.Token, newCoupon coupons.Coupon) (coupons.Coupon, error) {
	ret := _m.Called(token, newCoupon)

	var r0 coupons.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, coupons.Coupon) (coupons.Coupon, error)); ok {
		return rf(token, newCoupon)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, coupons.Coupon) coupons.Coupon); ok {
		r0 = rf(token, newCoupon)
	} else {
		r0 = ret.Get(0).(coupons.Coupon)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, coupons.Coupon) error); ok {
		r1 = rf(token, newCoupon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
